services:
  - type: web
    name: sistema-pos
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    ports:
      - port: 3000
        env: PORT
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
    healthcheckPath: /api/version
    autoDeploy: true
    branch: master
